replicaCount: 2
fullname: "python-service"

image:
  repository: mokchhedul/url_python-service
  tag: "d7455d4bd0ec66f4d76d1bd36c4ddedc7f9d45b6"
  pullPolicy: Always

service:
  port: 5000
  type: ClusterIP

env:
  GO_SERVICE_URL: "http://go-service:8000"
  NODE_SERVICE_URL: "http://node-service:3000"
  REDIS_URL: "redis:6379"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 60
  targetMemory: 70
