sonar.projectKey=urlshortener-microservices
sonar.projectName=URL Shortener Microservices
sonar.host.url=http://54.234.27.75:9000
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/deploy/**
sonar.token=${SONAR_TOKEN}
