replicaCount: 2
fullname: "go-service"

image:
  repository: mokchhedul/go-service
  tag: "d7455d4bd0ec66f4d76d1bd36c4ddedc7f9d45b6"
  pullPolicy: Always

service:
  port: 8000
  type: ClusterIP

env:
  REDIS_URL: "redis:6379"
  PYTHON_SERVICE_URL: "http://python-service:5000"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 60
  targetMemory: 70
