apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: url-shortener-project
  namespace: argocd
spec:
  description: "Microservice project for URL shortener"
  sourceRepos:
    - "*"
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
