apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-service-app
  # namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: python-image=mokchhedul/python-service
    argocd-image-updater.argoproj.io/python-image.update-strategy: digest
    argocd-image-updater.argoproj.io/python-image.allow-tags: regexp:^([a-f0-9]{7,40})$
    argocd-image-updater.argoproj.io/python-image.container-name: python-service
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds

spec:
  project: url-shortener-project
  source:
    repoURL: 'https://github.com/mdmokchhedulislam/urs_shortner_microservice.git'
    targetRevision: main
    path: k8s/python
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true          
      - ApplyOutOfSyncOnly=true
