apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
  labels:
    app.kubernetes.io/name: redis
spec: 
  project: url-shortener-project
  source:
    repoURL: 'https://github.com/mdmokchhedulislam/urs_shortner_microservice.git'
    targetRevision: main
    path: k8s/redis
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true          
      - ApplyOutOfSyncOnly=true
